- name: Configure DB Server
  hosts: db
  become: yes
  vars:
    MY_SQL_PASSWORD: ExpenseApp@1
    LOGIN_HOST: db.harshadevops.site
  tasks:
    - name: Install mysql-server
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: Enable and Start mysql-server
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Install Python MySQL Dependencies
      ansible.builtin.pip:
        name:
          - PyMySQL
          - cryptography
        executable: pip3.9

    - name: Checking DB connection to verify if password is already set
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ MY_SQL_PASSWORD }}"
        login_host: "{{ LOGIN_HOST }}"
      ignore_errors: true
      register: mysql_connection_output
