- name: Install nginx server
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Start and Enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Run App Prerequisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-preq

- name: Copy frontend conf
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
    - Restart nginx
